### ISSUE TITLE
Deal with codes that are also relationships

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/uk-geo-utils#15]
Consider the following model:

```python
class Foo(models.Model):
    lad = models.ForeignKey(
        "councils.Council", 
        on_delete=models.CASCADE, 
        blank=True, 
        max_length=9, 
        db_column="lad"
    )
```

This model is assigned as `ONSUD_MODEL`.

When using `get_codes("lad")`, the code returned is the related model. If the `lad` field isn't a relationship, then the code value is returned.

This is because `get_code` is doing the following:

```python
codes = set([getattr(u, code_type) for u in self._uprns])
```

If the actual code is the expected return type, then I think the above line needs to become:

```python
code_type_field = self.onsud_model._meta.get_field(code_type)
codes = set([getattr(u, code_type_field.attname) for u in self._uprns])
```

Of course, it might be useful to have the related model returned, but it does produce slightly unexpected results.

**Comment by chris48s** [comment]
Agreed :+1:  . `get_code()` should always return a string GSS code.
